#pragma config(Sensor, in1,    photo,          sensorReflection)
#pragma config(Sensor, in8,    salinity,       sensorAnalog)
#pragma config(Sensor, dgtl1,  anemBack,       sensorRotation)
#pragma config(Sensor, dgtl2,  anemFront,      sensorRotation)
#pragma config(Sensor, dgtl6,  ledGreen,       sensorDigitalOut)
#pragma config(Sensor, dgtl8,  ledRed,         sensorDigitalOut)
#pragma config(Sensor, dgtl10, ledOrange,      sensorDigitalOut)
#pragma config(Sensor, dgtl12, ledBlue,        sensorDigitalOut)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           crane,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int ROT_90_POWER = 50;

typedef struct {
	int speed;

} robot;

bool manualControl = true;

/*void moveForward(int power)
{
	motor[motorA] = -power;
	motor[motorB] = power;
	motor[motorC] = -power;
	motor[motorD] = power;
}*/

void moveForward(double dist)
{
	motor[frontLeft] = 1000;
	motor[backLeft] = 1000;
	motor[frontRight] = 1000;
	motor[backRight] = 1000;
	wait1Msec(dist * 17);
}

void rotate(int angle)
{
	int sign = 1;
	if (angle < 0) sign = -1;

	motor[frontLeft] = sign * ROT_90_POWER;
	motor[backLeft] = sign * ROT_90_POWER;
	motor[frontRight] = -sign * ROT_90_POWER;
	motor[backRight] = -sign * ROT_90_POWER;
	wait1Msec((int) (angle/90.0*1700));
}

void rotateCrane(int angle)
{
	//motor[crane] = (angle / 180.0) * 127;
	motor[crane] = 63;
	//setServo(crane, 127);
	wait1Msec(1000);
}

void setLed(int port, int val)
{
	SensorValue[port] = val;
}

void output4Bits(int num)
{
	setLed(ledBlue, (num & 1) >> 0);
	setLed(ledOrange, (num & 2) >> 1);
	setLed(ledRed, (num & 4) >> 2);
	setLed(ledGreen, (num & 8) >> 3);
	wait1Msec(2000);
	setLed(ledBlue, 0);
	setLed(ledOrange, 0);
	setLed(ledRed, 0);
	setLed(ledGreen, 0);
}

void update() {
	if (manualControl) {
		// Left joystick controls left side
		int leftPower = vexRT[Ch3] / 4;
		// Right joystick controls right side
		int rightPower = vexRT[Ch2] / 4;

		// Boost
		if (vexRT[Btn6U]) {
			leftPower *= 2;
			rightPower *= 2;
		}
		// Brake
		if (vexRT[Btn5U]){
			leftPower = 0;
			rightPower = 0;
		}

		motor[frontLeft] = leftPower;
		motor[backLeft] = leftPower;
		motor[frontRight] = -rightPower;
		motor[backRight] = -rightPower;
	}
}

task main()
{
	//moveForward(50);
	//wait1Msec(1000);
	//moveForward(-50, 1000);
	//rotate(-50, 3000);
	//manualControl = true;
	manualControl = false;

	//rotate(60);
	//moveForward(30.5);
	//rotateCrane(30);

	/* Salinity calibration
	 * Fresh water = 0b0011 xx11
	 * Salt water = 0b0010 xxxx
	 */
	output4Bits(SensorValue[salinity]);

	if (manualControl) {
		while (true) {
			update();
		}
	}

}
